# Load Packages

In [1]:
import pandas as pd
import numpy as np
import pickle as pickle
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn import svm
from sklearn.metrics import matthews_corrcoef, make_scorer
from sklearn.model_selection import GridSearchCV

# Import Data

In [2]:
train_set = pd.read_csv("../data/clean/twitter_training_clean.csv", index_col=0)
test_set = pd.read_csv("../data/clean/twitter_test_clean.csv", index_col=0)
val_set = pd.read_csv("../data/clean/twitter_validation_clean.csv", index_col=0)

X_train = train_set.drop(labels="Sentiment", axis=1)
y_train = train_set["Sentiment"]

X_test = test_set.drop(labels="Sentiment", axis=1)
y_test = test_set["Sentiment"]

X_val = val_set.drop(labels="Sentiment", axis=1)
y_val = val_set["Sentiment"]

In [3]:
X_train

,Tweet Id,Entity,Tweet Content
49181,6122,FIFA,Last Weekend league for Fifa 20 Glad I could f...
43259,10298,PlayerUnknownsBattlegrounds(PUBG),omg i'm so excited to watch dk play pubg
55405,2398,CallOfDuty,all others who have problems with
14766,2956,Dota2,in
43611,10362,PlayerUnknownsBattlegrounds(PUBG),"minho, felix de jeongin sucked at pubg pretty ..."
...,...,...,...
37194,5237,Hearthstone,you
6265,289,Amazon,I'm not even going to show a 7-2 loss.
54886,2311,CallOfDuty,Fuck this call of duty update..
860,2553,Borderlands,I should get up & feed my dogs & such that way...
15795,3131,Dota2,Welcome to The International!

In [4]:
X_val

,Tweet Id,Entity,Tweet Content
60857,4926,GrandTheftAuto(GTA),Looks to me like he failed to check out the wa...
44454,11709,Verizon,"Wow, it takes all sorts of crazy people out th..."
72986,9020,Nvidia,Nvidia Unveils The World’s Fastest Gaming Moni...
36360,8295,Microsoft,Huge radio play here. Reinvention / Corporate ...
2299,1604,CallOfDutyBlackopsColdWar,SO I HAPPY WHO ABOUT THIS.
...,...,...,...
12476,8571,NBA2K,@Ronnie2K where is all my Mamba Edition extras...
49149,6117,FIFA,Sell 700k fifa coins fucking this game
12173,8517,NBA2K,@NBA2K $ 107 for a four game break and I can't...
4319,1949,CallOfDutyBlackopsColdWar,has called me a madman.. I understood right fr...
52128,10638,RedDeadRedemption(RDR),RDR2 at 31m makes really this boy super happy.

## Encoding

In [5]:
encoder = OrdinalEncoder()
encoder = encoder.fit(X_train)
X_train = encoder.transform(X_train)

encoder = encoder.fit(X_val)
X_val = encoder.transform(X_val)

encoder = encoder.fit(X_test)
X_test = encoder.transform(X_test)

In [6]:
X_train

array([[5.9300e+03, 1.0000e+01, 3.0056e+04],
       [1.0001e+04, 2.4000e+01, 5.3175e+04],
       [2.3370e+03, 6.0000e+00, 4.9602e+04],
       ...,
       [2.2500e+03, 6.0000e+00, 1.8167e+04],
       [2.4840e+03, 4.0000e+00, 2.4862e+04],
       [3.0470e+03, 9.0000e+00, 4.6437e+04]], shape=(59196, 3))

In [7]:
X_val

array([[3.4980e+03, 1.4000e+01, 7.8000e+03],
       [8.2960e+03, 2.8000e+01, 1.2301e+04],
       [6.4040e+03, 2.1000e+01, 8.6150e+03],
       ...,
       [6.0360e+03, 2.0000e+01, 1.7920e+03],
       [1.3890e+03, 7.0000e+00, 1.3116e+04],
       [7.5300e+03, 2.5000e+01, 9.2460e+03]], shape=(14800, 3))

In [8]:
X_test

array([[263.,  11., 419.],
       [ 28.,   0., 213.],
       [646.,  19.,  91.],
       ...,
       [205.,   4., 780.],
       [632.,  19., 228.],
       [542.,  31., 501.]], shape=(1000, 3))

## Scaling

In [9]:
scaler = StandardScaler(with_mean=False)
X_train = scaler.fit_transform(X_train)
X_val = scaler.fit_transform(X_val)

In [10]:
X_train

array([[1.65263951, 1.08352099, 1.84175933],
       [2.78719186, 2.60045038, 3.25843599],
       [0.65130161, 0.65011259, 3.03949115],
       ...,
       [0.62705546, 0.65011259, 1.11323003],
       [0.69226923, 0.4334084 , 1.52348351],
       [0.84917244, 0.97516889, 2.84554757]], shape=(59196, 3))

In [11]:
X_val

array([[1.33514751, 1.51690283, 1.87125225],
       [3.16649049, 3.03380566, 2.95106076],
       [2.44433523, 2.27535424, 2.06677412],
       ...,
       [2.30387374, 2.16700404, 0.42990821],
       [0.53016578, 0.75845141, 3.14658263],
       [2.87411685, 2.70875505, 2.21815363]], shape=(14800, 3))

In [12]:
X_test

array([[263.,  11., 419.],
       [ 28.,   0., 213.],
       [646.,  19.,  91.],
       ...,
       [205.,   4., 780.],
       [632.,  19., 228.],
       [542.,  31., 501.]], shape=(1000, 3))

# Model

In [13]:
svc = svm.LinearSVC(random_state=42)
matthews_scorer = make_scorer(matthews_corrcoef)

## Hyperparameter Search

In [14]:
param_grid = {
    "loss": ["hinge", "squared_hinge"],
    "dual": [True, False],
    "C": [0.01, 0.1, 0.5, 1.0],
    "max_iter": [500, 1000, 2000, 5000, 10000, 20000]
}

grid_search = GridSearchCV(svc, param_grid, scoring=matthews_scorer, verbose=3)
grid_search.fit(X_train, y_train)

grid_search.cv_results_

Fitting 5 folds for each of 96 candidates, totalling 480 fits
[CV 1/5] END C=0.01, dual=True, loss=hinge, max_iter=500;, score=-0.003 total time=   0.1s
[CV 2/5] END C=0.01, dual=True, loss=hinge, max_iter=500;, score=-0.026 total time=   0.1s
[CV 3/5] END C=0.01, dual=True, loss=hinge, max_iter=500;, score=-0.027 total time=   0.1s
[CV 4/5] END C=0.01, dual=True, loss=hinge, max_iter=500;, score=-0.000 total time=   0.1s
[CV 5/5] END C=0.01, dual=True, loss=hinge, max_iter=500;, score=0.041 total time=   0.1s
[CV 1/5] END C=0.01, dual=True, loss=hinge, max_iter=1000;, score=-0.003 total time=   0.1s
[CV 2/5] END C=0.01, dual=True, loss=hinge, max_iter=1000;, score=-0.026 total time=   0.1s
[CV 3/5] END C=0.01, dual=True, loss=hinge, max_iter=1000;, score=-0.027 total time=   0.1s
[CV 4/5] END C=0.01, dual=True, loss=hinge, max_iter=1000;, score=-0.000 total time=   0.1s
[CV 5/5] END C=0.01, dual=True, loss=hinge, max_iter=1000;, score=0.041 total time=   0.1s
[CV 1/5] END C=0.01, dual=True, loss=hinge, max_iter=2000;, score=-0.003 total time=   0.1s
[CV 2/5] END C=0.01, dual=True, loss=hinge, max_iter=2000;, score=-0.026 total time=   0.1s
[CV 3/5] END C=0.01, dual=True, loss=hinge, max_iter=2000;, score=-0.027 total time=   0.1s
[CV 4/5] END C=0.01, dual=True, loss=hinge, max_iter=2000;, score=-0.000 total time=   0.1s
[CV 5/5] END C=0.01, dual=True, loss=hinge, max_iter=2000;, score=0.041 total time=   0.1s
[CV 1/5] END C=0.01, dual=True, loss=hinge, max_iter=5000;, score=-0.003 total time=   0.1s
[CV 2/5] END C=0.01, dual=True, loss=hinge, max_iter=5000;, score=-0.026 total time=   0.1s
[CV 3/5] END C=0.01, dual=True, loss=hinge, max_iter=5000;, score=-0.027 total time=   0.1s
[CV 4/5] END C=0.01, dual=True, loss=hinge, max_iter=5000;, score=-0.000 total time=   0.1s
[CV 5/5] END C=0.01, dual=True, loss=hinge, max_iter=5000;, score=0.041 total time=   0.1s
[CV 1/5] END C=0.01, dual=True, loss=hinge, max_iter=10000;, score=-0.003 total time=   0.1s
[CV 2/5] END C=0.01, dual=True, loss=hinge, max_iter=10000;, score=-0.026 total time=   0.0s
[CV 3/5] END C=0.01, dual=True, loss=hinge, max_iter=10000;, score=-0.027 total time=   0.0s
[CV 4/5] END C=0.01, dual=True, loss=hinge, max_iter=10000;, score=-0.000 total time=   0.0s
[CV 5/5] END C=0.01, dual=True, loss=hinge, max_iter=10000;, score=0.041 total time=   0.1s
[CV 1/5] END C=0.01, dual=True, loss=hinge, max_iter=20000;, score=-0.003 total time=   0.0s
[CV 2/5] END C=0.01, dual=True, loss=hinge, max_iter=20000;, score=-0.026 total time=   0.0s
[CV 3/5] END C=0.01, dual=True, loss=hinge, max_iter=20000;, score=-0.027 total time=   0.1s
[CV 4/5] END C=0.01, dual=True, loss=hinge, max_iter=20000;, score=-0.000 total time=   0.1s
[CV 5/5] END C=0.01, dual=True, loss=hinge, max_iter=20000;, score=0.041 total time=   0.1s
[CV 1/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=500;, score=0.060 total time=   0.3s
[CV 2/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=500;, score=0.046 total time=   0.3s
[CV 3/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=500;, score=0.056 total time=   0.4s
[CV 4/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=500;, score=0.041 total time=   0.7s
[CV 5/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=500;, score=0.057 total time=   0.4s
[CV 1/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=1000;, score=0.060 total time=   0.4s
[CV 2/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=1000;, score=0.046 total time=   0.6s
[CV 3/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=1000;, score=0.056 total time=   0.5s
[CV 4/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=1000;, score=0.041 total time=   0.5s
[CV 5/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=1000;, score=0.057 total time=   0.5s
[CV 1/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=2000;, score=0.060 total time=   0.5s
[CV 2/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=2000;, score=0.046 total time=   0.5s
[CV 3/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=2000;, score=0.056 total time=   0.5s
[CV 4/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=2000;, score=0.041 total time=   0.5s
[CV 5/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=2000;, score=0.057 total time=   0.5s
[CV 1/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=5000;, score=0.060 total time=   0.5s
[CV 2/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=5000;, score=0.046 total time=   0.5s
[CV 3/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=5000;, score=0.056 total time=   0.4s
[CV 4/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=5000;, score=0.041 total time=   0.4s
[CV 5/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=5000;, score=0.057 total time=   0.7s
[CV 1/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=10000;, score=0.060 total time=   0.6s
[CV 2/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=10000;, score=0.046 total time=   0.5s
[CV 3/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=10000;, score=0.056 total time=   0.4s
[CV 4/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=10000;, score=0.041 total time=   0.3s
[CV 5/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=10000;, score=0.057 total time=   0.4s
[CV 1/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=20000;, score=0.060 total time=   0.3s
[CV 2/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=20000;, score=0.046 total time=   0.2s
[CV 3/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=20000;, score=0.056 total time=   0.2s
[CV 4/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=20000;, score=0.041 total time=   0.4s
[CV 5/5] END C=0.01, dual=True, loss=squared_hinge, max_iter=20000;, score=0.057 total time=   0.4s
[CV 1/5] END C=0.01, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 2/5] END C=0.01, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 3/5] END C=0.01, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 4/5] END C=0.01, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 5/5] END C=0.01, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 1/5] END C=0.01, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 2/5] END C=0.01, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 3/5] END C=0.01, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 4/5] END C=0.01, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 5/5] END C=0.01, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 1/5] END C=0.01, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 2/5] END C=0.01, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 3/5] END C=0.01, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 4/5] END C=0.01, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 5/5] END C=0.01, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 1/5] END C=0.01, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 2/5] END C=0.01, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 3/5] END C=0.01, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 4/5] END C=0.01, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 5/5] END C=0.01, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 1/5] END C=0.01, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 2/5] END C=0.01, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 3/5] END C=0.01, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 4/5] END C=0.01, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 5/5] END C=0.01, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 1/5] END C=0.01, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 2/5] END C=0.01, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 3/5] END C=0.01, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 4/5] END C=0.01, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 5/5] END C=0.01, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.1s
[CV 1/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=500;, score=0.059 total time=   0.2s
[CV 2/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=500;, score=0.046 total time=   0.3s
[CV 3/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=500;, score=0.056 total time=   0.1s
[CV 4/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=500;, score=0.041 total time=   0.1s
[CV 5/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=500;, score=0.057 total time=   0.2s
[CV 1/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=1000;, score=0.059 total time=   0.3s
[CV 2/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=1000;, score=0.046 total time=   0.4s
[CV 3/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=1000;, score=0.056 total time=   0.1s
[CV 4/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=1000;, score=0.041 total time=   0.2s
[CV 5/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=1000;, score=0.057 total time=   0.3s
[CV 1/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=2000;, score=0.059 total time=   0.2s
[CV 2/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=2000;, score=0.046 total time=   0.2s
[CV 3/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=2000;, score=0.056 total time=   0.2s
[CV 4/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=2000;, score=0.041 total time=   0.4s
[CV 5/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=2000;, score=0.057 total time=   0.3s
[CV 1/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=5000;, score=0.059 total time=   0.2s
[CV 2/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=5000;, score=0.046 total time=   0.4s
[CV 3/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=5000;, score=0.056 total time=   0.2s
[CV 4/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=5000;, score=0.041 total time=   0.3s
[CV 5/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=5000;, score=0.057 total time=   0.2s
[CV 1/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=10000;, score=0.059 total time=   0.3s
[CV 2/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=10000;, score=0.046 total time=   0.6s
[CV 3/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=10000;, score=0.056 total time=   0.7s
[CV 4/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=10000;, score=0.041 total time=   1.1s
[CV 5/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=10000;, score=0.057 total time=   0.2s
[CV 1/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=20000;, score=0.059 total time=   0.4s
[CV 2/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=20000;, score=0.046 total time=   0.2s
[CV 3/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=20000;, score=0.056 total time=   0.2s
[CV 4/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=20000;, score=0.041 total time=   0.2s
[CV 5/5] END C=0.01, dual=False, loss=squared_hinge, max_iter=20000;, score=0.057 total time=   0.2s
[CV 1/5] END C=0.1, dual=True, loss=hinge, max_iter=500;, score=-0.016 total time=   0.2s
[CV 2/5] END C=0.1, dual=True, loss=hinge, max_iter=500;, score=-0.003 total time=   0.2s
[CV 3/5] END C=0.1, dual=True, loss=hinge, max_iter=500;, score=0.036 total time=   0.2s
[CV 4/5] END C=0.1, dual=True, loss=hinge, max_iter=500;, score=0.016 total time=   0.2s
[CV 5/5] END C=0.1, dual=True, loss=hinge, max_iter=500;, score=0.007 total time=   0.2s
[CV 1/5] END C=0.1, dual=True, loss=hinge, max_iter=1000;, score=-0.016 total time=   0.2s
[CV 2/5] END C=0.1, dual=True, loss=hinge, max_iter=1000;, score=-0.003 total time=   0.2s
[CV 3/5] END C=0.1, dual=True, loss=hinge, max_iter=1000;, score=0.036 total time=   0.1s
[CV 4/5] END C=0.1, dual=True, loss=hinge, max_iter=1000;, score=0.016 total time=   0.1s
[CV 5/5] END C=0.1, dual=True, loss=hinge, max_iter=1000;, score=0.007 total time=   0.1s
[CV 1/5] END C=0.1, dual=True, loss=hinge, max_iter=2000;, score=-0.016 total time=   0.1s
[CV 2/5] END C=0.1, dual=True, loss=hinge, max_iter=2000;, score=-0.003 total time=   0.1s
[CV 3/5] END C=0.1, dual=True, loss=hinge, max_iter=2000;, score=0.036 total time=   0.3s
[CV 4/5] END C=0.1, dual=True, loss=hinge, max_iter=2000;, score=0.016 total time=   0.3s
[CV 5/5] END C=0.1, dual=True, loss=hinge, max_iter=2000;, score=0.007 total time=   0.1s
[CV 1/5] END C=0.1, dual=True, loss=hinge, max_iter=5000;, score=-0.016 total time=   0.1s
[CV 2/5] END C=0.1, dual=True, loss=hinge, max_iter=5000;, score=-0.003 total time=   0.1s
[CV 3/5] END C=0.1, dual=True, loss=hinge, max_iter=5000;, score=0.036 total time=   0.1s
[CV 4/5] END C=0.1, dual=True, loss=hinge, max_iter=5000;, score=0.016 total time=   0.4s
[CV 5/5] END C=0.1, dual=True, loss=hinge, max_iter=5000;, score=0.007 total time=   0.1s
[CV 1/5] END C=0.1, dual=True, loss=hinge, max_iter=10000;, score=-0.016 total time=   0.2s
[CV 2/5] END C=0.1, dual=True, loss=hinge, max_iter=10000;, score=-0.003 total time=   0.1s
[CV 3/5] END C=0.1, dual=True, loss=hinge, max_iter=10000;, score=0.036 total time=   0.1s
[CV 4/5] END C=0.1, dual=True, loss=hinge, max_iter=10000;, score=0.016 total time=   0.1s
[CV 5/5] END C=0.1, dual=True, loss=hinge, max_iter=10000;, score=0.007 total time=   0.1s
[CV 1/5] END C=0.1, dual=True, loss=hinge, max_iter=20000;, score=-0.016 total time=   0.2s
[CV 2/5] END C=0.1, dual=True, loss=hinge, max_iter=20000;, score=-0.003 total time=   0.1s
[CV 3/5] END C=0.1, dual=True, loss=hinge, max_iter=20000;, score=0.036 total time=   0.2s
[CV 4/5] END C=0.1, dual=True, loss=hinge, max_iter=20000;, score=0.016 total time=   0.1s
[CV 5/5] END C=0.1, dual=True, loss=hinge, max_iter=20000;, score=0.007 total time=   0.1s
[CV 1/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=500;, score=0.060 total time=   1.7s
[CV 2/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=500;, score=0.046 total time=   2.3s
[CV 3/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=500;, score=0.057 total time=   2.5s
[CV 4/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=500;, score=0.041 total time=   3.2s
[CV 5/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=500;, score=0.057 total time=   1.3s
[CV 1/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=1000;, score=0.060 total time=   1.2s
[CV 2/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=1000;, score=0.046 total time=   1.2s
[CV 3/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=1000;, score=0.057 total time=   1.2s
[CV 4/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=1000;, score=0.041 total time=   1.4s
[CV 5/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=1000;, score=0.057 total time=   1.3s
[CV 1/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=2000;, score=0.060 total time=   1.2s
[CV 2/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=2000;, score=0.046 total time=   1.2s
[CV 3/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=2000;, score=0.057 total time=   1.2s
[CV 4/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=2000;, score=0.041 total time=   1.2s
[CV 5/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=2000;, score=0.057 total time=   1.2s
[CV 1/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=5000;, score=0.060 total time=   1.5s
[CV 2/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=5000;, score=0.046 total time=   1.2s
[CV 3/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=5000;, score=0.057 total time=   1.3s
[CV 4/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=5000;, score=0.041 total time=   1.4s
[CV 5/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=5000;, score=0.057 total time=   1.5s
[CV 1/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=10000;, score=0.060 total time=   1.2s
[CV 2/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=10000;, score=0.046 total time=   1.1s
[CV 3/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=10000;, score=0.057 total time=   1.5s
[CV 4/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=10000;, score=0.041 total time=   1.3s
[CV 5/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=10000;, score=0.057 total time=   1.2s
[CV 1/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=20000;, score=0.060 total time=   1.3s
[CV 2/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=20000;, score=0.046 total time=   1.2s
[CV 3/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=20000;, score=0.057 total time=   1.2s
[CV 4/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=20000;, score=0.041 total time=   1.6s
[CV 5/5] END C=0.1, dual=True, loss=squared_hinge, max_iter=20000;, score=0.057 total time=   1.3s
[CV 1/5] END C=0.1, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 2/5] END C=0.1, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 3/5] END C=0.1, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 4/5] END C=0.1, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 5/5] END C=0.1, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 1/5] END C=0.1, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 2/5] END C=0.1, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 3/5] END C=0.1, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 4/5] END C=0.1, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 5/5] END C=0.1, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 1/5] END C=0.1, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 2/5] END C=0.1, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 3/5] END C=0.1, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 4/5] END C=0.1, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 5/5] END C=0.1, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 1/5] END C=0.1, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 2/5] END C=0.1, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 3/5] END C=0.1, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 4/5] END C=0.1, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 5/5] END C=0.1, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 1/5] END C=0.1, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 2/5] END C=0.1, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 3/5] END C=0.1, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 4/5] END C=0.1, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 5/5] END C=0.1, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 1/5] END C=0.1, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 2/5] END C=0.1, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 3/5] END C=0.1, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 4/5] END C=0.1, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 5/5] END C=0.1, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 1/5] END C=0.1, dual=False, loss=squared_hinge, max_iter=500;, score=0.060 total time=   0.1s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV 5/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=500;, score=0.057 total time=   6.9s
[CV 1/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=1000;, score=0.060 total time=   5.7s
[CV 2/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=1000;, score=0.046 total time=   6.2s
[CV 3/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=1000;, score=0.056 total time=   6.1s
[CV 4/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=1000;, score=0.041 total time=   6.2s
[CV 5/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=1000;, score=0.057 total time=   9.2s
[CV 1/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=2000;, score=0.060 total time=   7.1s
[CV 2/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=2000;, score=0.046 total time=   6.9s
[CV 3/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=2000;, score=0.056 total time=   6.7s
[CV 4/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=2000;, score=0.041 total time=   8.1s
[CV 5/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=2000;, score=0.057 total time=  17.8s
[CV 1/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=5000;, score=0.060 total time=  12.4s
[CV 2/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=5000;, score=0.046 total time=  12.2s
[CV 3/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=5000;, score=0.056 total time=  11.3s
[CV 4/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=5000;, score=0.041 total time=  10.9s
[CV 5/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=5000;, score=0.057 total time=  12.7s
[CV 1/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=10000;, score=0.060 total time=  13.6s
[CV 2/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=10000;, score=0.046 total time=   8.0s
[CV 3/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=10000;, score=0.056 total time=   6.1s
[CV 4/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=10000;, score=0.041 total time=   9.0s
[CV 5/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=10000;, score=0.057 total time=  10.5s
[CV 1/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=20000;, score=0.060 total time=   8.0s
[CV 2/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=20000;, score=0.046 total time=   8.7s
[CV 3/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=20000;, score=0.056 total time=   9.5s
[CV 4/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=20000;, score=0.041 total time=   8.1s
[CV 5/5] END C=0.5, dual=True, loss=squared_hinge, max_iter=20000;, score=0.057 total time=   8.9s
[CV 1/5] END C=0.5, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 2/5] END C=0.5, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 3/5] END C=0.5, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 4/5] END C=0.5, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 5/5] END C=0.5, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 1/5] END C=0.5, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 2/5] END C=0.5, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 3/5] END C=0.5, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 4/5] END C=0.5, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 5/5] END C=0.5, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 1/5] END C=0.5, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 2/5] END C=0.5, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 3/5] END C=0.5, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 4/5] END C=0.5, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 5/5] END C=0.5, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 1/5] END C=0.5, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 2/5] END C=0.5, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 3/5] END C=0.5, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 4/5] END C=0.5, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 5/5] END C=0.5, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 1/5] END C=0.5, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 2/5] END C=0.5, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 3/5] END C=0.5, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 4/5] END C=0.5, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 5/5] END C=0.5, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 1/5] END C=0.5, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 2/5] END C=0.5, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 3/5] END C=0.5, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 4/5] END C=0.5, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 5/5] END C=0.5, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 1/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=500;, score=0.060 total time=   0.1s
[CV 2/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=500;, score=0.046 total time=   0.1s
[CV 3/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=500;, score=0.056 total time=   0.1s
[CV 4/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=500;, score=0.041 total time=   0.1s
[CV 5/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=500;, score=0.057 total time=   0.1s
[CV 1/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=1000;, score=0.060 total time=   0.2s
[CV 2/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=1000;, score=0.046 total time=   0.2s
[CV 3/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=1000;, score=0.056 total time=   0.2s
[CV 4/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=1000;, score=0.041 total time=   0.2s
[CV 5/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=1000;, score=0.057 total time=   0.2s
[CV 1/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=2000;, score=0.060 total time=   0.2s
[CV 2/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=2000;, score=0.046 total time=   0.2s
[CV 3/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=2000;, score=0.056 total time=   0.2s
[CV 4/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=2000;, score=0.041 total time=   0.2s
[CV 5/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=2000;, score=0.057 total time=   0.2s
[CV 1/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=5000;, score=0.060 total time=   0.2s
[CV 2/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=5000;, score=0.046 total time=   0.1s
[CV 3/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=5000;, score=0.056 total time=   0.2s
[CV 4/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=5000;, score=0.041 total time=   0.3s
[CV 5/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=5000;, score=0.057 total time=   0.2s
[CV 1/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=10000;, score=0.060 total time=   0.2s
[CV 2/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=10000;, score=0.046 total time=   0.2s
[CV 3/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=10000;, score=0.056 total time=   0.2s
[CV 4/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=10000;, score=0.041 total time=   0.2s
[CV 5/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=10000;, score=0.057 total time=   0.1s
[CV 1/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=20000;, score=0.060 total time=   0.1s
[CV 2/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=20000;, score=0.046 total time=   0.1s
[CV 3/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=20000;, score=0.056 total time=   0.1s
[CV 4/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=20000;, score=0.041 total time=   0.1s
[CV 5/5] END C=0.5, dual=False, loss=squared_hinge, max_iter=20000;, score=0.057 total time=   0.1s
[CV 1/5] END C=1.0, dual=True, loss=hinge, max_iter=500;, score=0.040 total time=   0.4s
[CV 2/5] END C=1.0, dual=True, loss=hinge, max_iter=500;, score=0.007 total time=   0.4s
[CV 3/5] END C=1.0, dual=True, loss=hinge, max_iter=500;, score=0.056 total time=   0.5s
[CV 4/5] END C=1.0, dual=True, loss=hinge, max_iter=500;, score=0.015 total time=   0.4s
[CV 5/5] END C=1.0, dual=True, loss=hinge, max_iter=500;, score=0.015 total time=   0.7s
[CV 1/5] END C=1.0, dual=True, loss=hinge, max_iter=1000;, score=0.040 total time=   0.4s
[CV 2/5] END C=1.0, dual=True, loss=hinge, max_iter=1000;, score=0.007 total time=   0.5s
[CV 3/5] END C=1.0, dual=True, loss=hinge, max_iter=1000;, score=0.056 total time=   0.5s
[CV 4/5] END C=1.0, dual=True, loss=hinge, max_iter=1000;, score=0.015 total time=   0.6s
[CV 5/5] END C=1.0, dual=True, loss=hinge, max_iter=1000;, score=0.015 total time=   0.4s
[CV 1/5] END C=1.0, dual=True, loss=hinge, max_iter=2000;, score=0.040 total time=   0.4s
[CV 2/5] END C=1.0, dual=True, loss=hinge, max_iter=2000;, score=0.007 total time=   0.4s
[CV 3/5] END C=1.0, dual=True, loss=hinge, max_iter=2000;, score=0.056 total time=   0.6s
[CV 4/5] END C=1.0, dual=True, loss=hinge, max_iter=2000;, score=0.015 total time=   0.4s
[CV 5/5] END C=1.0, dual=True, loss=hinge, max_iter=2000;, score=0.015 total time=   0.5s
[CV 1/5] END C=1.0, dual=True, loss=hinge, max_iter=5000;, score=0.040 total time=   0.6s
[CV 2/5] END C=1.0, dual=True, loss=hinge, max_iter=5000;, score=0.007 total time=   0.5s
[CV 3/5] END C=1.0, dual=True, loss=hinge, max_iter=5000;, score=0.056 total time=   0.4s
[CV 4/5] END C=1.0, dual=True, loss=hinge, max_iter=5000;, score=0.015 total time=   0.6s
[CV 5/5] END C=1.0, dual=True, loss=hinge, max_iter=5000;, score=0.015 total time=   0.6s
[CV 1/5] END C=1.0, dual=True, loss=hinge, max_iter=10000;, score=0.040 total time=   0.5s
[CV 2/5] END C=1.0, dual=True, loss=hinge, max_iter=10000;, score=0.007 total time=   0.4s
[CV 3/5] END C=1.0, dual=True, loss=hinge, max_iter=10000;, score=0.056 total time=   0.5s
[CV 4/5] END C=1.0, dual=True, loss=hinge, max_iter=10000;, score=0.015 total time=   0.5s
[CV 5/5] END C=1.0, dual=True, loss=hinge, max_iter=10000;, score=0.015 total time=   0.5s
[CV 1/5] END C=1.0, dual=True, loss=hinge, max_iter=20000;, score=0.040 total time=   0.6s
[CV 2/5] END C=1.0, dual=True, loss=hinge, max_iter=20000;, score=0.007 total time=   0.5s
[CV 3/5] END C=1.0, dual=True, loss=hinge, max_iter=20000;, score=0.056 total time=   0.6s
[CV 4/5] END C=1.0, dual=True, loss=hinge, max_iter=20000;, score=0.015 total time=   0.7s
[CV 5/5] END C=1.0, dual=True, loss=hinge, max_iter=20000;, score=0.015 total time=   0.5s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV 1/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=500;, score=0.060 total time=  11.8s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV 2/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=500;, score=0.046 total time=   9.9s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV 3/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=500;, score=0.056 total time=  13.4s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV 4/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=500;, score=0.041 total time=  14.2s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV 5/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=500;, score=0.057 total time=  26.8s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV 1/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=1000;, score=0.060 total time=  29.3s
[CV 2/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=1000;, score=0.046 total time=  15.0s
[CV 3/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=1000;, score=0.056 total time=  16.6s
[CV 4/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=1000;, score=0.041 total time=  15.4s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[CV 5/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=1000;, score=0.057 total time=  19.3s
[CV 1/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=2000;, score=0.060 total time=  19.4s
[CV 2/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=2000;, score=0.046 total time=  14.3s
[CV 3/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=2000;, score=0.056 total time=  15.3s
[CV 4/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=2000;, score=0.041 total time=  16.6s
[CV 5/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=2000;, score=0.057 total time=  20.7s
[CV 1/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=5000;, score=0.060 total time=  14.8s
[CV 2/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=5000;, score=0.046 total time=  16.1s
[CV 3/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=5000;, score=0.056 total time=  14.7s
[CV 4/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=5000;, score=0.041 total time=  16.3s
[CV 5/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=5000;, score=0.057 total time=  27.1s
[CV 1/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=10000;, score=0.060 total time=  18.9s
[CV 2/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=10000;, score=0.046 total time=  16.4s
[CV 3/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=10000;, score=0.056 total time=  16.0s
[CV 4/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=10000;, score=0.041 total time=  18.1s
[CV 5/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=10000;, score=0.057 total time=  19.5s
[CV 1/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=20000;, score=0.060 total time=  13.9s
[CV 2/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=20000;, score=0.046 total time=  18.2s
[CV 3/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=20000;, score=0.056 total time=  18.9s
[CV 4/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=20000;, score=0.041 total time=  17.4s
[CV 5/5] END C=1.0, dual=True, loss=squared_hinge, max_iter=20000;, score=0.057 total time=  21.4s
[CV 1/5] END C=1.0, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 2/5] END C=1.0, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 3/5] END C=1.0, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 4/5] END C=1.0, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 5/5] END C=1.0, dual=False, loss=hinge, max_iter=500;, score=nan total time=   0.0s
[CV 1/5] END C=1.0, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 2/5] END C=1.0, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 3/5] END C=1.0, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 4/5] END C=1.0, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 5/5] END C=1.0, dual=False, loss=hinge, max_iter=1000;, score=nan total time=   0.0s
[CV 1/5] END C=1.0, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 2/5] END C=1.0, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 3/5] END C=1.0, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 4/5] END C=1.0, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 5/5] END C=1.0, dual=False, loss=hinge, max_iter=2000;, score=nan total time=   0.0s
[CV 1/5] END C=1.0, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 2/5] END C=1.0, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 3/5] END C=1.0, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 4/5] END C=1.0, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 5/5] END C=1.0, dual=False, loss=hinge, max_iter=5000;, score=nan total time=   0.0s
[CV 1/5] END C=1.0, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 2/5] END C=1.0, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 3/5] END C=1.0, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 4/5] END C=1.0, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 5/5] END C=1.0, dual=False, loss=hinge, max_iter=10000;, score=nan total time=   0.0s
[CV 1/5] END C=1.0, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 2/5] END C=1.0, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 3/5] END C=1.0, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 4/5] END C=1.0, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 5/5] END C=1.0, dual=False, loss=hinge, max_iter=20000;, score=nan total time=   0.0s
[CV 1/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=500;, score=0.060 total time=   0.2s
[CV 2/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=500;, score=0.046 total time=   0.1s
[CV 3/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=500;, score=0.056 total time=   0.2s
[CV 4/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=500;, score=0.041 total time=   0.1s
[CV 5/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=500;, score=0.057 total time=   0.1s
[CV 1/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=1000;, score=0.060 total time=   0.1s
[CV 2/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=1000;, score=0.046 total time=   0.2s
[CV 3/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=1000;, score=0.056 total time=   0.1s
[CV 4/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=1000;, score=0.041 total time=   0.1s
[CV 5/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=1000;, score=0.057 total time=   0.1s
[CV 1/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=2000;, score=0.060 total time=   0.2s
[CV 2/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=2000;, score=0.046 total time=   0.1s
[CV 3/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=2000;, score=0.056 total time=   0.1s
[CV 4/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=2000;, score=0.041 total time=   0.1s
[CV 5/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=2000;, score=0.057 total time=   0.1s
[CV 1/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=5000;, score=0.060 total time=   0.1s
[CV 2/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=5000;, score=0.046 total time=   0.1s
[CV 3/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=5000;, score=0.056 total time=   0.1s
[CV 4/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=5000;, score=0.041 total time=   0.2s
[CV 5/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=5000;, score=0.057 total time=   0.2s
[CV 1/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=10000;, score=0.060 total time=   0.2s
[CV 2/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=10000;, score=0.046 total time=   0.1s
[CV 3/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=10000;, score=0.056 total time=   0.1s
[CV 4/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=10000;, score=0.041 total time=   0.1s
[CV 5/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=10000;, score=0.057 total time=   0.1s
[CV 1/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=20000;, score=0.060 total time=   0.1s
[CV 2/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=20000;, score=0.046 total time=   0.2s
[CV 3/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=20000;, score=0.056 total time=   0.2s
[CV 4/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=20000;, score=0.041 total time=   0.1s
[CV 5/5] END C=1.0, dual=False, loss=squared_hinge, max_iter=20000;, score=0.057 total time=   0.1s

C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
120 fits failed out of a total of 480.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
120 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_classes.py", line 321, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
                                           ^^^^^^^^^^^^^^^
  File "C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py", line 1229, in _fit_liblinear
    solver_type = _get_liblinear_solver_type(multi_class, penalty, loss, dual)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\svm\_base.py", line 1060, in _get_liblinear_solver_type
    raise ValueError(
ValueError: Unsupported set of arguments: The combination of penalty='l2' and loss='hinge' are not supported when dual=False, Parameters: penalty='l2', loss='hinge', dual=False

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ttjaa\Documents\College Part II\CSCI-635\csci-635-project\.venv\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [-0.00303187 -0.00303187 -0.00303187 -0.00303187 -0.00303187 -0.00303187
  0.05171575  0.05171575  0.05171575  0.05171575  0.05171575  0.05171575
         nan         nan         nan         nan         nan         nan
  0.05166132  0.05166132  0.05166132  0.05166132  0.05166132  0.05166132
  0.00796156  0.00796156  0.00796156  0.00796156  0.00796156  0.00796156
  0.05190568  0.05190568  0.05190568  0.05190568  0.05190568  0.05190568
         nan         nan         nan         nan         nan         nan
  0.05196002  0.05196002  0.05196002  0.05196002  0.05196002  0.05196002
  0.00017719  0.00017719  0.00017719  0.00017719  0.00017719  0.00017719
  0.0519058   0.0519058   0.0519058   0.0519058   0.0519058   0.0519058
         nan         nan         nan         nan         nan         nan
  0.0519058   0.0519058   0.0519058   0.0519058   0.0519058   0.0519058
  0.02638245  0.02638245  0.02638245  0.02638245  0.02638245  0.02638245
  0.0519058   0.0519058   0.0519058   0.0519058   0.0519058   0.0519058
         nan         nan         nan         nan         nan         nan
  0.0519058   0.0519058   0.0519058   0.0519058   0.0519058   0.0519058 ]
  warnings.warn(

{'mean_fit_time': array([ 0.18251085,  0.17402658,  0.18319654,  0.17815652,  0.13453617,
         0.13449259,  0.51082768,  0.56693425,  0.57921791,  0.57556009,
         0.50277276,  0.40354838,  0.08959341,  0.0586442 ,  0.06065884,
         0.06040735,  0.06677904,  0.08084221,  0.2513762 ,  0.35446897,
         0.31160765,  0.32524681,  0.62368255,  0.33240452,  0.26321478,
         0.2217042 ,  0.25761085,  0.25701556,  0.203405  ,  0.217026  ,
         2.27269869,  1.3609653 ,  1.26434579,  1.45109696,  1.34618988,
         1.39841967,  0.05766263,  0.0716476 ,  0.0682313 ,  0.05718679,
         0.06676083,  0.06094604,  0.18038425,  0.17460356,  0.18092327,
         0.20392094,  0.18725009,  0.17704091,  0.37878833,  0.31396055,
         0.392068  ,  0.44370542,  0.47357335,  0.48831244,  6.4899004 ,
         6.75332723,  9.39240265, 11.96776533,  9.49727311,  8.71594105,
         0.05773339,  0.05508647,  0.06013355,  0.06800799,  0.06140203,
         0.05850687,  0.21949768,  0.27535815,  0.27412171,  0.27819796,
         0.2671021 ,  0.1940383 ,  0.58738408,  0.56819139,  0.54277525,
         0.62089229,  0.55682774,  0.65050616, 15.29016166, 19.1812325 ,
        17.33787088, 17.85036259, 17.87427864, 18.02112412,  0.06423159,
         0.05770655,  0.05431151,  0.05272956,  0.05845871,  0.06036639,
         0.22912903,  0.21783919,  0.20493703,  0.22315388,  0.21133561,
         0.21565795]),
 'std_fit_time': array([1.80601684e-02, 8.71912534e-03, 6.38821653e-03, 2.94732171e-02,
        7.57767341e-03, 5.55682483e-03, 1.22291558e-01, 6.75412885e-02,
        2.13865454e-02, 1.15637238e-01, 9.53521906e-02, 7.15668192e-02,
        2.45921051e-02, 4.97727500e-03, 7.75009640e-03, 8.03966630e-03,
        1.01162921e-02, 3.93532810e-02, 5.44670646e-02, 1.01299216e-01,
        7.09983411e-02, 6.59373176e-02, 2.88804540e-01, 9.56021056e-02,
        2.80765881e-02, 4.75920574e-02, 7.93176414e-02, 1.28274661e-01,
        4.08708431e-02, 3.30129561e-02, 6.45992749e-01, 7.10606907e-02,
        1.93147967e-02, 1.01505616e-01, 1.16051247e-01, 1.55097271e-01,
        4.51725341e-03, 1.59271376e-02, 7.29514418e-03, 8.96768648e-03,
        5.53573669e-03, 7.93224895e-03, 1.57970125e-02, 8.24315342e-03,
        1.33195505e-02, 2.68390730e-02, 1.56942679e-02, 1.02023494e-02,
        1.26434124e-01, 1.12749155e-02, 7.04530468e-02, 9.53369625e-02,
        1.36020640e-01, 8.54738458e-02, 3.61252456e-01, 1.27268666e+00,
        4.25722317e+00, 6.83725205e-01, 2.51910921e+00, 5.46144485e-01,
        4.72598667e-03, 1.91190507e-03, 6.06819862e-03, 1.74743316e-02,
        8.26660771e-03, 3.51183903e-03, 9.24597851e-03, 2.96383696e-02,
        2.28152174e-02, 3.67863188e-02, 3.00695809e-02, 2.03028651e-02,
        1.00401247e-01, 5.49939222e-02, 5.94910666e-02, 8.07915188e-02,
        1.77595821e-02, 7.73131855e-02, 5.91685458e+00, 5.29173260e+00,
        2.43685359e+00, 4.69305874e+00, 1.34909289e+00, 2.43902214e+00,
        8.99981039e-03, 5.58048482e-03, 2.72120715e-03, 2.99204136e-03,
        2.92276561e-03, 4.17726734e-03, 2.75183105e-02, 1.83754250e-02,
        1.72636088e-02, 4.07832832e-02, 3.00270513e-02, 3.15605683e-02]),
 'mean_score_time': array([0.0267365 , 0.02441602, 0.02432332, 0.02552891, 0.0183394 ,
        0.01826539, 0.0214817 , 0.02392068, 0.02399373, 0.02113795,
        0.02588496, 0.0266284 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.02152987, 0.02154212,
        0.02995906, 0.02809849, 0.06464267, 0.02616138, 0.02473059,
        0.02515807, 0.02897496, 0.02237945, 0.02575593, 0.02148876,
        0.02746067, 0.01555023, 0.0162075 , 0.02504406, 0.01563864,
        0.01545362, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01569386, 0.01625628, 0.01546226,
        0.0196312 , 0.01628036, 0.0204988 , 0.01949682, 0.01593952,
        0.02099462, 0.02411318, 0.03058815, 0.02488756, 0.01793747,
        0.01956353, 0.02255297, 0.02999005, 0.02011838, 0.02268434,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.01740851, 0.02454095, 0.02224479, 0.02699056,
        0.01975698, 0.01563392, 0.01813111, 0.01633234, 0.01856189,
        0.0190805 , 0.01768484, 0.01987972, 0.03814354, 0.02080946,
        0.01755872, 0.0191927 , 0.01738176, 0.02718506, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.01946993, 0.0170918 , 0.01915021, 0.01919699, 0.01919332,
        0.02351594]),
 'std_score_time': array([0.00389908, 0.00229005, 0.00359934, 0.00734386, 0.0035106 ,
        0.00137852, 0.00410061, 0.00796887, 0.00074989, 0.00453045,
        0.01166863, 0.01177556, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.00767168, 0.00456491,
        0.00984493, 0.00749907, 0.05066485, 0.00649993, 0.00254461,
        0.0038296 , 0.00632076, 0.00484275, 0.00603278, 0.00324426,
        0.01198521, 0.00045686, 0.00103396, 0.00945114, 0.00060974,
        0.00034185, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.0007909 , 0.00101129, 0.00062121,
        0.00449041, 0.00196229, 0.00643385, 0.00681881, 0.00082673,
        0.00659104, 0.01056794, 0.00965518, 0.00496888, 0.0028809 ,
        0.0046891 , 0.00578776, 0.00752766, 0.00444366, 0.00719271,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.0008609 , 0.00649541, 0.00201579, 0.00735909,
        0.00497872, 0.00193947, 0.00323784, 0.00165469, 0.00258175,
        0.00326884, 0.0029959 , 0.00351705, 0.03897837, 0.00492061,
        0.00139654, 0.00563596, 0.00367113, 0.00428326, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00469931, 0.00245423, 0.00212929, 0.00383185, 0.00158938,
        0.00399733]),
 'param_C': masked_array(data=[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
                    0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
                    0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.5, 0.5,
                    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
                    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=1e+20),
 'param_dual': masked_array(data=[True, True, True, True, True, True, True, True, True,
                    True, True, True, False, False, False, False, False,
                    False, False, False, False, False, False, False, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, False, False, False, False, False, False,
                    False, False, False, False, False, False, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, False, False, False, False, False, False, False,
                    False, False, False, False, False, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=True),
 'param_loss': masked_array(data=['hinge', 'hinge', 'hinge', 'hinge', 'hinge', 'hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'hinge', 'hinge', 'hinge', 'hinge', 'hinge', 'hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'hinge', 'hinge', 'hinge', 'hinge', 'hinge', 'hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'hinge', 'hinge', 'hinge', 'hinge', 'hinge', 'hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'hinge', 'hinge', 'hinge', 'hinge', 'hinge', 'hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'hinge', 'hinge', 'hinge', 'hinge', 'hinge', 'hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'hinge', 'hinge', 'hinge', 'hinge', 'hinge', 'hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'hinge', 'hinge', 'hinge', 'hinge', 'hinge', 'hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge',
                    'squared_hinge', 'squared_hinge', 'squared_hinge'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_max_iter': masked_array(data=[500, 1000, 2000, 5000, 10000, 20000, 500, 1000, 2000,
                    5000, 10000, 20000, 500, 1000, 2000, 5000, 10000,
                    20000, 500, 1000, 2000, 5000, 10000, 20000, 500, 1000,
                    2000, 5000, 10000, 20000, 500, 1000, 2000, 5000, 10000,
                    20000, 500, 1000, 2000, 5000, 10000, 20000, 500, 1000,
                    2000, 5000, 10000, 20000, 500, 1000, 2000, 5000, 10000,
                    20000, 500, 1000, 2000, 5000, 10000, 20000, 500, 1000,
                    2000, 5000, 10000, 20000, 500, 1000, 2000, 5000, 10000,
                    20000, 500, 1000, 2000, 5000, 10000, 20000, 500, 1000,
                    2000, 5000, 10000, 20000, 500, 1000, 2000, 5000, 10000,
                    20000, 500, 1000, 2000, 5000, 10000, 20000],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'C': 0.01, 'dual': True, 'loss': 'hinge', 'max_iter': 500},
  {'C': 0.01, 'dual': True, 'loss': 'hinge', 'max_iter': 1000},
  {'C': 0.01, 'dual': True, 'loss': 'hinge', 'max_iter': 2000},
  {'C': 0.01, 'dual': True, 'loss': 'hinge', 'max_iter': 5000},
  {'C': 0.01, 'dual': True, 'loss': 'hinge', 'max_iter': 10000},
  {'C': 0.01, 'dual': True, 'loss': 'hinge', 'max_iter': 20000},
  {'C': 0.01, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 500},
  {'C': 0.01, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 1000},
  {'C': 0.01, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 2000},
  {'C': 0.01, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 5000},
  {'C': 0.01, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 10000},
  {'C': 0.01, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 20000},
  {'C': 0.01, 'dual': False, 'loss': 'hinge', 'max_iter': 500},
  {'C': 0.01, 'dual': False, 'loss': 'hinge', 'max_iter': 1000},
  {'C': 0.01, 'dual': False, 'loss': 'hinge', 'max_iter': 2000},
  {'C': 0.01, 'dual': False, 'loss': 'hinge', 'max_iter': 5000},
  {'C': 0.01, 'dual': False, 'loss': 'hinge', 'max_iter': 10000},
  {'C': 0.01, 'dual': False, 'loss': 'hinge', 'max_iter': 20000},
  {'C': 0.01, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 500},
  {'C': 0.01, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 1000},
  {'C': 0.01, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 2000},
  {'C': 0.01, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 5000},
  {'C': 0.01, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 10000},
  {'C': 0.01, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 20000},
  {'C': 0.1, 'dual': True, 'loss': 'hinge', 'max_iter': 500},
  {'C': 0.1, 'dual': True, 'loss': 'hinge', 'max_iter': 1000},
  {'C': 0.1, 'dual': True, 'loss': 'hinge', 'max_iter': 2000},
  {'C': 0.1, 'dual': True, 'loss': 'hinge', 'max_iter': 5000},
  {'C': 0.1, 'dual': True, 'loss': 'hinge', 'max_iter': 10000},
  {'C': 0.1, 'dual': True, 'loss': 'hinge', 'max_iter': 20000},
  {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 500},
  {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 1000},
  {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 2000},
  {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 5000},
  {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 10000},
  {'C': 0.1, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 20000},
  {'C': 0.1, 'dual': False, 'loss': 'hinge', 'max_iter': 500},
  {'C': 0.1, 'dual': False, 'loss': 'hinge', 'max_iter': 1000},
  {'C': 0.1, 'dual': False, 'loss': 'hinge', 'max_iter': 2000},
  {'C': 0.1, 'dual': False, 'loss': 'hinge', 'max_iter': 5000},
  {'C': 0.1, 'dual': False, 'loss': 'hinge', 'max_iter': 10000},
  {'C': 0.1, 'dual': False, 'loss': 'hinge', 'max_iter': 20000},
  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 500},
  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 1000},
  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 2000},
  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 5000},
  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 10000},
  {'C': 0.1, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 20000},
  {'C': 0.5, 'dual': True, 'loss': 'hinge', 'max_iter': 500},
  {'C': 0.5, 'dual': True, 'loss': 'hinge', 'max_iter': 1000},
  {'C': 0.5, 'dual': True, 'loss': 'hinge', 'max_iter': 2000},
  {'C': 0.5, 'dual': True, 'loss': 'hinge', 'max_iter': 5000},
  {'C': 0.5, 'dual': True, 'loss': 'hinge', 'max_iter': 10000},
  {'C': 0.5, 'dual': True, 'loss': 'hinge', 'max_iter': 20000},
  {'C': 0.5, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 500},
  {'C': 0.5, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 1000},
  {'C': 0.5, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 2000},
  {'C': 0.5, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 5000},
  {'C': 0.5, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 10000},
  {'C': 0.5, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 20000},
  {'C': 0.5, 'dual': False, 'loss': 'hinge', 'max_iter': 500},
  {'C': 0.5, 'dual': False, 'loss': 'hinge', 'max_iter': 1000},
  {'C': 0.5, 'dual': False, 'loss': 'hinge', 'max_iter': 2000},
  {'C': 0.5, 'dual': False, 'loss': 'hinge', 'max_iter': 5000},
  {'C': 0.5, 'dual': False, 'loss': 'hinge', 'max_iter': 10000},
  {'C': 0.5, 'dual': False, 'loss': 'hinge', 'max_iter': 20000},
  {'C': 0.5, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 500},
  {'C': 0.5, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 1000},
  {'C': 0.5, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 2000},
  {'C': 0.5, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 5000},
  {'C': 0.5, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 10000},
  {'C': 0.5, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 20000},
  {'C': 1.0, 'dual': True, 'loss': 'hinge', 'max_iter': 500},
  {'C': 1.0, 'dual': True, 'loss': 'hinge', 'max_iter': 1000},
  {'C': 1.0, 'dual': True, 'loss': 'hinge', 'max_iter': 2000},
  {'C': 1.0, 'dual': True, 'loss': 'hinge', 'max_iter': 5000},
  {'C': 1.0, 'dual': True, 'loss': 'hinge', 'max_iter': 10000},
  {'C': 1.0, 'dual': True, 'loss': 'hinge', 'max_iter': 20000},
  {'C': 1.0, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 500},
  {'C': 1.0, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 1000},
  {'C': 1.0, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 2000},
  {'C': 1.0, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 5000},
  {'C': 1.0, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 10000},
  {'C': 1.0, 'dual': True, 'loss': 'squared_hinge', 'max_iter': 20000},
  {'C': 1.0, 'dual': False, 'loss': 'hinge', 'max_iter': 500},
  {'C': 1.0, 'dual': False, 'loss': 'hinge', 'max_iter': 1000},
  {'C': 1.0, 'dual': False, 'loss': 'hinge', 'max_iter': 2000},
  {'C': 1.0, 'dual': False, 'loss': 'hinge', 'max_iter': 5000},
  {'C': 1.0, 'dual': False, 'loss': 'hinge', 'max_iter': 10000},
  {'C': 1.0, 'dual': False, 'loss': 'hinge', 'max_iter': 20000},
  {'C': 1.0, 'dual': False, 'loss': 'squared_hinge', 'max_iter': 500},

In [15]:
best_svc = grid_search.best_estimator_

## Training

In [16]:
train_score = best_svc.score(X_train, y_train)

In [17]:
print("Training Score: ", train_score)

Training Score:  0.3239576998445841

## Validation

In [18]:
val_score = best_svc.score(X_val, y_val)

print("Validation Score: ", val_score)

Validation Score:  0.3170945945945946

## Test

In [19]:
test_score = best_svc.score(X_test, y_test)

print("Test Score: ", test_score)

Test Score:  0.277